name: CI/CD Taller

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
      - name: Verificar existencia de archivos
        run: |
          if [ ! -f home.html ]; echo 'Error: Falta home.html'; exit 1; fi
          if [ ! -f styles.css ]; echo 'Error: Falta styles.css'; exit 1; fi
          echo 'Archivos verificados correctamente'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simular despliegue
        run: echo 'listos para el despliegue'
